// Code generated by mockery v1.0.0. DO NOT EDIT.

package mock

import (
	mock "github.com/stretchr/testify/mock"
	entity "github.com/wade-sam/fyp-backup-server/entity"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: policy
func (_m *MockRepository) Create(policy *entity.Policy) (*entity.Policy, error) {
	ret := _m.Called(policy)

	var r0 *entity.Policy
	if rf, ok := ret.Get(0).(func(*entity.Policy) *entity.Policy); ok {
		r0 = rf(policy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Policy)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*entity.Policy) error); ok {
		r1 = rf(policy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: name
func (_m *MockRepository) Delete(name string) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: name
func (_m *MockRepository) Get(name string) (*entity.Policy, error) {
	ret := _m.Called(name)

	var r0 *entity.Policy
	if rf, ok := ret.Get(0).(func(string) *entity.Policy); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Policy)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields:
func (_m *MockRepository) List() ([]*entity.Policy, error) {
	ret := _m.Called()

	var r0 []*entity.Policy
	if rf, ok := ret.Get(0).(func() []*entity.Policy); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Policy)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: policy
func (_m *MockRepository) Update(policy *entity.Policy) error {
	ret := _m.Called(policy)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Policy) error); ok {
		r0 = rf(policy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
