// Code generated by mockery v1.0.0. DO NOT EDIT.

package mock

import (
	mock "github.com/stretchr/testify/mock"
	entity "github.com/wade-sam/fyp-backup-server/entity"
)

// MockReader is an autogenerated mock type for the Reader type
type MockReader struct {
	mock.Mock
}

// Get provides a mock function with given fields: name
func (_m *MockReader) Get(name string) (*entity.Policy, error) {
	ret := _m.Called(name)

	var r0 *entity.Policy
	if rf, ok := ret.Get(0).(func(string) *entity.Policy); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Policy)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields:
func (_m *MockReader) List() ([]*entity.Policy, error) {
	ret := _m.Called()

	var r0 []*entity.Policy
	if rf, ok := ret.Get(0).(func() []*entity.Policy); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Policy)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
